#ifndef RASPBERRYPIGPIOINTERFACE_H
#define RASPBERRYPIGPIOINTERFACE_H

#include <QtCore/qglobal.h>

#if defined(RASPBERRYPIGPIO_LIBRARY)
#  define RASPBERRYPIGPIOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RASPBERRYPIGPIOSHARED_EXPORT Q_DECL_IMPORT
#endif

class RASPBERRYPIGPIOSHARED_EXPORT RaspberryPiGPIOInterface
{

public:
    RaspberryPiGPIOInterface();
};

#endif // RASPBERRYPIGPIOINTERFACE_H
